# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: xindan's little world
url: wangxindan.com


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /:year/:month/:day/:title
auto: true
pygments: true
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  use_coderay: false
